#!/bin/bash
# ==============================================================================
# Bash script to install openfn-devtools
# ==============================================================================

if [[ $1 ]]; then
  # install a language-package if argument is provided
  echo installing language-$1...
  git clone https://github.com/OpenFn/language-$1.git
  cd language-$1
  npm install
  cd ../
  echo language-$1 installed ✓
else
  # base installation
  echo installing openfn-devtools...
  git submodule init
  git submodule update

  cd language-common
  npm install
  cd ../

  cd fn-lang
  npm install
  cd ../

  echo openfn-devtools installed ✓
fi
