# Project information
site_name: 'OpenFn/devtools'
site_description: 'Developer tools for OpenFn/core, adaptors, and expression writing.'
site_author: 'OpenFn'
site_url: 'https://openfn.github.io/devtools'
use_directory_urls: false

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/openfn/docs'

# Copyright
copyright: 'Copyright (c) 2020 Open Function Group LLC'

plugins:
  - search

extra_javascript: [freshChat.js]

# Documentation and theme
docs_dir: 'docs'
theme:
  logo: images/logo.svg
  icon:
    # logo: material/cloud
    repo: fontawesome/brands/github-alt
  name: 'material'
  features:
    - tabs
    - instant
  palette:
    scheme: default
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - 'Home': index.md
  - 'Deploying': deploying.md

# Options
extra:
  # disqus: openfn
  author:
    github: 'openfn'
    twitter: 'openfn'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openfn
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/openfn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openfn
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/openfn

# Google Analytics
google_analytics:
  - '253755419'
  - 'openfn.org'

# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: '#'
