#!/usr/bin/env bash

while read repo
do
  if [[ ! -d "$repo" ]]; then
    echo "Cloning $repo..."
    git clone --depth=1 "git@github.com:OpenFn/$repo.git" ./adaptors/$repo
    if [[ $1 = "npm-install" ]]; then
      npm install --prefix ./adaptors/$repo
    else
      echo "Skipping npm install for $repo"
    fi
  fi

  if [[ ! -f "./adaptors/$repo/.git/hooks/post-commit" ]]; then
    echo "Adding post-commit hook to $repo..."
    cp scripts/post-commit "./adaptors/$repo/.git/hooks/post-commit"
  fi
done < repos

# Ensure we have a doclets directory
mkdir -p doclets

# Ensure we have a builds directory
mkdir -p builds

# Get node dependencies
npm install